export const SET_SELECTED_ROW_DATA = 'SET_SELECTED_ROW_DATA'
export const SET_TABLE_DATA_FROM_STORAGE = 'SET_TABLE_DATA_FROM_STORAGE'
export const REMOVE_SELECTED_ROW_DATA = 'REMOVE_SELECTED_ROW_DATA'
export const ADD_DATA_TO_THE_STORAGE = 'ADD_DATA_TO_THE_STORAGE'
